title: Hi, I'm Evrim.
email: hi@evrim.io
description: Hi, I'm Evrim. I'm a web and mobile app developer based in Dubai.
url: https://evrim.io
author:
  name: Evrim Persembe
  twitter: evrimfeyyaz
  picture: /public/evrim-persembe.jpg


# SEO
twitter:
  username: evrimfeyyaz
  card: summary
logo: /public/logo.png
social:
  links:
  - https://twitter.com/evrimfeyyaz
  - https://github.com/evrimfeyyaz
  - https://instagram.com/evrimfeyyaz
google_site_verification: ujLWhEJm2rf00JVXp_MQTxYZoAKA6cGmqNE18rlu7fU
defaults:
  - scope:
      path: ""
    values:
      image: /public/logo-social.png


# Projects
collections:
  projects:
    output: true
    permalink: /projects/:name/


# Build settings
permalink: /:title/
sass:
  style: compressed

plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-redirect-from


# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
